[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/mahmud-picks.m3u"
  [headers.values]
    Content-Type = "application/x-mpegurl"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/IPTV-Flow-World-Cup.m3u"
  [headers.values]
    Content-Type = "application/x-mpegurl"
    Cache-Control = "public, max-age=300"
