'use client';

// LOGO_DICTIONARY: Direct exact channel mappings provided by the user.
// Maps exact/case-insensitive channel names directly to Wikipedia-hosted optimized PNG/SVG files.
const LOGO_DICTIONARY = {
  "somoy tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Somoy_Television_Logo.svg/200px-Somoy_Television_Logo.svg.png",
  "somoy tv new": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Somoy_Television_Logo.svg/200px-Somoy_Television_Logo.svg.png",
  "ntv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/NTV_Bangladesh_Logo.svg/200px-NTV_Bangladesh_Logo.svg.png",
  "rtv": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/RTV_Bangladesh.svg/200px-RTV_Bangladesh.svg.png",
  "btv": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/BTV_Logo.svg/200px-BTV_Logo.svg.png",
  "btv  bangladesh": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/BTV_Logo.svg/200px-BTV_Logo.svg.png",
  "btv bangladesh": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/BTV_Logo.svg/200px-BTV_Logo.svg.png",
  "jamuna tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Jamuna_Television_Logo.svg/200px-Jamuna_Television_Logo.svg.png",
  "ekattor tv hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ekattor_TV_Logo.svg/200px-Ekattor_TV_Logo.svg.png",
  "channel i": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/ChannelIBD.svg/200px-ChannelIBD.svg.png",
  "channel 24": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Channel_24_Bangladesh.svg/200px-Channel_24_Bangladesh.svg.png",
  "channel 9 hd": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Channel_9_Bangladesh.png/200px-Channel_9_Bangladesh.png",
  "channel 1 news 4k": "https://upload.wikimedia.org/wikipedia/en/a/a2/Channel_1_Bangladesh.png",
  "atn news hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/ATN_Bangla.svg/200px-ATN_Bangla.svg.png",
  "deepto tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Deepto_TV_logo.svg/200px-Deepto_TV_logo.svg.png",
  "news 24": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/News24_Bangladesh_logo.svg/200px-News24_Bangladesh_logo.svg.png",
  "dbc news": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/DBC_News_logo.svg/200px-DBC_News_logo.svg.png",
  "maasranga tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Maasranga_Television.svg/200px-Maasranga_Television.svg.png",
  "bangla vision": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/BanglaVision_TV_logo.svg/200px-BanglaVision_TV_logo.svg.png",
  "star news bd": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Star_News_Bangladesh.png/200px-Star_News_Bangladesh.png",
  "ananda tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Ananda_TV_Logo.svg/200px-Ananda_TV_Logo.svg.png",
  "boishakhi tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Boishakhi_Media_Limited.svg/200px-Boishakhi_Media_Limited.svg.png",
  "bangla tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Bangla_TV_logo.svg/200px-Bangla_TV_logo.svg.png",
  "desh tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Desh_TV_logo.svg/200px-Desh_TV_logo.svg.png",
  "sa tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/SA_Television.svg/200px-SA_Television.svg.png",
  "ekhon tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ekhon_TV.png/200px-Ekhon_TV.png",
  "ekushe tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/ETV_Bangladesh.svg/200px-ETV_Bangladesh.svg.png",
  "independent tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Independent_Television_Bangladesh.svg/200px-Independent_Television_Bangladesh.svg.png",
  "my tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/MyTV_Bangladesh.png/200px-MyTV_Bangladesh.png",
  "nexus tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Nexus_Television_Bangladesh.png/200px-Nexus_Television_Bangladesh.png",
  "rajdhani tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Rajdhani_TV.png/200px-Rajdhani_TV.png",
  "duronto live": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Duronto_TV.png/200px-Duronto_TV.png",
  "channel s tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Channel_S_logo.svg/200px-Channel_S_logo.svg.png",
  "t sports hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/T_Sports_logo.svg/200px-T_Sports_logo.svg.png",
  "fifa 2026 — t sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/T_Sports_logo.svg/200px-T_Sports_logo.svg.png",
  "fifa 2026 — t sports alt": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/T_Sports_logo.svg/200px-T_Sports_logo.svg.png",
  "fifa 2026 — btv": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/BTV_Logo.svg/200px-BTV_Logo.svg.png",
  "fifa 2026 — somoy tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Somoy_Television_Logo.svg/200px-Somoy_Television_Logo.svg.png",
  "somoy fifa world cup 2026": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Somoy_Television_Logo.svg/200px-Somoy_Television_Logo.svg.png",
  "fifa world cup 2026": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "football world cup 2026 sky": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "football world cup 2026 (fox sports)": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "coze tv fifa world cup 2026": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "fussball.tv 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "fussball.tv 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png",
  "bein sports 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 3": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 4": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 4 amagi": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports xtra": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 1 alt": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein xtra (720)": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 1 au": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 2 au": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 3 au": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 1 1080p": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 2 1080p": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 3 1080p": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 4 1080p": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 5 1080p": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 1 turkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 2 turkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 3 turkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports 4 turkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sport extra ñ": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein sports ñ": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "bein xtra ñ *2": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png",
  "espn": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/200px-ESPN_wordmark.svg.png",
  "fox sports 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Fox_Sports_logo_%282019%29.svg/200px-Fox_Sports_logo_%282019%29.svg.png",
  "fox sports (720)": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Fox_Sports_logo_%282019%29.svg/200px-Fox_Sports_logo_%282019%29.svg.png",
  "fox ny": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/FOX_wordmark.svg/200px-FOX_wordmark.svg.png",
  "fox 11 green bay wi (wluk)": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/FOX_wordmark.svg/200px-FOX_wordmark.svg.png",
  "fifa 2026 — fox sports 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Fox_Sports_logo_%282019%29.svg/200px-Fox_Sports_logo_%282019%29.svg.png",
  "star sports 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Star_Sports_logo.svg/200px-Star_Sports_logo.svg.png",
  "star sports 1 alt": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Star_Sports_logo.svg/200px-Star_Sports_logo.svg.png",
  "real madrid tv": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/200px-Real_Madrid_CF.svg.png",
  "real madrid tv - english (oficial)": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/200px-Real_Madrid_CF.svg.png",
  "caze tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png",
  "caze tv br": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png",
  "caze tv (720)": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png",
  "caze tv 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png",
  "caze tv 3": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png",
  "redbull tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Red_Bull_TV_logo.svg/200px-Red_Bull_TV_logo.svg.png",
  "dazn fast+": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/DAZN_Logo.svg/200px-DAZN_Logo.svg.png",
  "dazn combat": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/DAZN_Logo.svg/200px-DAZN_Logo.svg.png",
  "dsports fhd": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/DIRECTV_Sports.svg/200px-DIRECTV_Sports.svg.png",
  "cignal tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cignal_TV_logo.png/200px-Cignal_TV_logo.png",
  "idmantv": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Idman_TV_logo.png/200px-Idman_TV_logo.png",
  "2tv sport": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/2TV_Georgia.png/200px-2TV_Georgia.png",
  "fight network": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Fight_Network_logo.svg/200px-Fight_Network_logo.svg.png",
  "fuel tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Fuel_TV_logo.svg/200px-Fuel_TV_logo.svg.png",
  "horse & country": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Horse_%26_Country_TV_logo.png/200px-Horse_%26_Country_TV_logo.png",
  "fubo sports 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/FuboTV_logo.svg/200px-FuboTV_logo.svg.png",
  "willow sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Willow_TV.png/200px-Willow_TV.png",
  "willow sports (1080p)": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Willow_TV.png/200px-Willow_TV.png",
  "willow hd tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Willow_TV.png/200px-Willow_TV.png",
  "cricket gold": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Cricket_Gold_logo.png/200px-Cricket_Gold_logo.png",
  "asports": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/ARY_Sports_logo.png/200px-ARY_Sports_logo.png",
  "ptv sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/PTV_Sports_logo.svg/200px-PTV_Sports_logo.svg.png",
  "fifa 2026 — ptv sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/PTV_Sports_logo.svg/200px-PTV_Sports_logo.svg.png",
  "tyc sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/TyC_Sports_Logo.svg/200px-TyC_Sports_Logo.svg.png",
  "fifa 2026 — tyc sports": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/TyC_Sports_Logo.svg/200px-TyC_Sports_Logo.svg.png",
  "tsn 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/TSN_2018.svg/200px-TSN_2018.svg.png",
  "tsn 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/TSN_2018.svg/200px-TSN_2018.svg.png",
  "tsn 3": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/TSN_2018.svg/200px-TSN_2018.svg.png",
  "a spor": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/A_Spor_logo.svg/200px-A_Spor_logo.svg.png",
  "sport italia": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sport_Italia_logo.png/200px-Sport_Italia_logo.png",
  "sport5": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sport5_logo.svg/200px-Sport5_logo.svg.png",
  "sportv 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/SporTV_logo.svg/200px-SporTV_logo.svg.png",
  "sportv 3": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/SporTV_logo.svg/200px-SporTV_logo.svg.png",
  "fx sports 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Fox_Sports_2_logo.svg/200px-Fox_Sports_2_logo.svg.png",
  "fx prem": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Fox_Sports_logo_%282019%29.svg/200px-Fox_Sports_logo_%282019%29.svg.png",
  "mtr sports-1": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/MTR_Sports.png/200px-MTR_Sports.png",
  "euro tv sports hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Eurosport_logo.svg/200px-Eurosport_logo.svg.png",
  "masr": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Al_Masriya_logo.png/200px-Al_Masriya_logo.png",
  "deporte - estrella tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Estrella_TV.svg/200px-Estrella_TV.svg.png",
  "azteca 7": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Azteca_7_logo.svg/200px-Azteca_7_logo.svg.png",
  "azteca 7a": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Azteca_7_logo.svg/200px-Azteca_7_logo.svg.png",
  "fancode": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/FanCode_logo.svg/200px-FanCode_logo.svg.png",
  "star jalsha": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Star_Jalsha.svg/200px-Star_Jalsha.svg.png",
  "zee bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Zee_Bangla.svg/200px-Zee_Bangla.svg.png",
  "colors bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Colors_Bangla_logo.svg/200px-Colors_Bangla_logo.svg.png",
  "republic bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Republic_Bangla_logo.svg/200px-Republic_Bangla_logo.svg.png",
  "republic bangla hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Republic_Bangla_logo.svg/200px-Republic_Bangla_logo.svg.png",
  "dd national hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Dd_national.svg/200px-Dd_national.svg.png",
  "etv josh": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/ETV_Josh_logo.png/200px-ETV_Josh_logo.png",
  "mazhavil manorama hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Mazhavil_Manorama_Logo.png/200px-Mazhavil_Manorama_Logo.png",
  "ptc punjabi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/PTC_Punjabi_logo.png/200px-PTC_Punjabi_logo.png",
  "ptc punjabi gold": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/PTC_Punjabi_logo.png/200px-PTC_Punjabi_logo.png",
  "roja tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Roja_TV.png/200px-Roja_TV.png",
  "suriya tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Surya_TV_logo.png/200px-Surya_TV_logo.png",
  "telugu one": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Telugu_One_logo.png/200px-Telugu_One_logo.png",
  "gtc punjabi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/GTC_Punjabi.png/200px-GTC_Punjabi.png",
  "goldmines": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Goldmines_Telefilms_logo.png/200px-Goldmines_Telefilms_logo.png",
  "goldmines movies": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Goldmines_Telefilms_logo.png/200px-Goldmines_Telefilms_logo.png",
  "goldmines bollywood": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Goldmines_Telefilms_logo.png/200px-Goldmines_Telefilms_logo.png",
  "sony max": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Sony_MAX_logo.svg/200px-Sony_MAX_logo.svg.png",
  "sony max hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Sony_MAX_logo.svg/200px-Sony_MAX_logo.svg.png",
  "sony max 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Sony_MAX_logo.svg/200px-Sony_MAX_logo.svg.png",
  "action hollywood": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Action_Hollywood_logo.png/200px-Action_Hollywood_logo.png",
  "raj digital plus": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Raj_TV_logo.png/200px-Raj_TV_logo.png",
  "9x tashan": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/9X_Tashan_logo.png/200px-9X_Tashan_logo.png",
  "9x jalwa": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/9X_Jalwa_logo.png/200px-9X_Jalwa_logo.png",
  "9x jalwa hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/9X_Jalwa_logo.png/200px-9X_Jalwa_logo.png",
  "9x jhakaas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/9X_Jhakaas_logo.png/200px-9X_Jhakaas_logo.png",
  "9xm": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/9XM_logo.svg/200px-9XM_logo.svg.png",
  "sangeet bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Sangeet_Bangla.png/200px-Sangeet_Bangla.png",
  "qello concerts": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Qello_logo.png/200px-Qello_logo.png",
  "etv music": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/ETV_Music_logo.png/200px-ETV_Music_logo.png",
  "raj musix tamil": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Raj_TV_logo.png/200px-Raj_TV_logo.png",
  "stingray classic rock": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "stingray djazz": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "stingray easy listening": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "stingray kpop": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "stingray naturescape": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "stingray the spa": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Stingray_Music_logo.png/200px-Stingray_Music_logo.png",
  "motu patlu": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Motu_Patlu_logo.png/200px-Motu_Patlu_logo.png",
  "tom & jerry tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tom_and_Jerry_logo.svg/200px-Tom_and_Jerry_logo.svg.png",
  "doraemon tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Doraemon_logo.png/200px-Doraemon_logo.png",
  "cartoon network": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/200px-Cartoon_Network_2010_logo.svg.png",
  "mr bean animated": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Mr_Bean_logo.png/200px-Mr_Bean_logo.png",
  "aaj tak hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Aaj_Tak.svg/200px-Aaj_Tak.svg.png",
  "abp news": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/ABP_News_Logo.svg/200px-ABP_News_Logo.svg.png",
  "abp ananda": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/ABP_Ananda_logo.svg/200px-ABP_Ananda_logo.svg.png",
  "abp asmita": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/ABP_News_Logo.svg/200px-ABP_News_Logo.svg.png",
  "abp ganga": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/ABP_News_Logo.svg/200px-ABP_News_Logo.svg.png",
  "ndtv mp chhattisgarh": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NDTV_logo.svg/200px-NDTV_logo.svg.png",
  "ndtv marathi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NDTV_logo.svg/200px-NDTV_logo.svg.png",
  "ndtv rajasthan": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NDTV_logo.svg/200px-NDTV_logo.svg.png",
  "ndtv profit": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NDTV_logo.svg/200px-NDTV_logo.svg.png",
  "news18 assam ne": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 bihar jharkhand": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 delhi ncr jk": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 gujarati": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 india": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 kannada": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 kerala": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 mp chhattisgarh": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 marathi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 odia": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 punjab haryana hp": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 rajasthan": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 tamil nadu": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 urdu": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "news18 up uttarakhand": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/News18_India.svg/200px-News18_India.svg.png",
  "republic tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Republic_TV_logo.svg/200px-Republic_TV_logo.svg.png",
  "republic bharat": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Republic_Bharat_logo.svg/200px-Republic_Bharat_logo.svg.png",
  "republic kannada": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Republic_TV_logo.svg/200px-Republic_TV_logo.svg.png",
  "dd news hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/DD_News_logo.svg/200px-DD_News_logo.svg.png",
  "etv news": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/ETV_News_logo.png/200px-ETV_News_logo.png",
  "zee news": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Zee_News_logo.svg/200px-Zee_News_logo.svg.png",
  "news nation": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/News_Nation.png/200px-News_Nation.png",
  "news9live": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/News9_logo.png/200px-News9_logo.png",
  "rt india": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/RT_logo.svg/200px-RT_logo.svg.png",
  "asianet suvarna news": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Suvarna_News_logo.png/200px-Suvarna_News_logo.png",
  "times now navbharat": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Times_Now_Navbharat.svg/200px-Times_Now_Navbharat.svg.png",
  "ntv telugu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/NTV_Telugu.png/200px-NTV_Telugu.png",
  "cnbc tv18": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/CNBC-TV18_logo.svg/200px-CNBC-TV18_logo.svg.png",
  "cnbc tv18 prime hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/CNBC-TV18_logo.svg/200px-CNBC-TV18_logo.svg.png",
  "cnbc awaas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/CNBC_Awaaz.svg/200px-CNBC_Awaaz.svg.png",
  "cnbc bajar": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/CNBC_Awaaz.svg/200px-CNBC_Awaaz.svg.png",
  "dd india": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/DD_India_logo.svg/200px-DD_India_logo.svg.png",
  "dd tamil": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/DD_Tamil_logo.png/200px-DD_Tamil_logo.png",
  "tv brics english": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/TV_BRICS_logo.png/200px-TV_BRICS_logo.png",
  "history tv18 hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/History_TV18_logo.svg/200px-History_TV18_logo.svg.png",
  "adventure earth": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Adventure_Earth_TV.png/200px-Adventure_Earth_TV.png",
  "sansad tv 1": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Sansad_TV_logo.svg/200px-Sansad_TV_logo.svg.png",
  "sansad tv 1 hd": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Sansad_TV_logo.svg/200px-Sansad_TV_logo.svg.png",
  "sansad tv 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Sansad_TV_logo.svg/200px-Sansad_TV_logo.svg.png",
  "etv comedy": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/ETV_Comedy_logo.png/200px-ETV_Comedy_logo.png",
  "peace tv bangla": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Peace_TV_logo.png/200px-Peace_TV_logo.png",
  "sanskar tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sanskar_TV_logo.png/200px-Sanskar_TV_logo.png",
  "sanskar web tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sanskar_TV_logo.png/200px-Sanskar_TV_logo.png",
  "shalom tv": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Shalom_TV_logo.svg/200px-Shalom_TV_logo.svg.png",
  "total bhakti": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Total_Bhakti_logo.png/200px-Total_Bhakti_logo.png",
  "mahaa bhakti": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/MahaBhakti_logo.png/200px-MahaBhakti_logo.png",
  "svbc sri venkateswara": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/SVBC_TV_logo.png/200px-SVBC_TV_logo.png",
  "svbc 2": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/SVBC_TV_logo.png/200px-SVBC_TV_logo.png",
  "svbc 4": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/SVBC_TV_logo.png/200px-SVBC_TV_logo.png",
  "quran": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Saudi_Quran_Channel_logo.svg/200px-Saudi_Quran_Channel_logo.svg.png"
};

// Keyword mapping for any secondary channels that might be added to the M3U later
const FALLBACK_LOGO_MAP = [
  { keywords: ['somoy'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Somoy_Television_Logo.svg/200px-Somoy_Television_Logo.svg.png' },
  { keywords: ['t sports', 'tsports'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/T_Sports_logo.svg/200px-T_Sports_logo.svg.png' },
  { keywords: ['caze'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Caze_TV_logo.png/200px-Caze_TV_logo.png' },
  { keywords: ['bein'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png' },
  { keywords: ['tsn'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/TSN_2018.svg/200px-TSN_2018.svg.png' },
  { keywords: ['espn'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/200px-ESPN_wordmark.svg.png' },
  { keywords: ['fox sports', 'fox sports 2', 'fox ny', 'fox 11', 'fx sports', 'fx prem'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Fox_Sports_logo_%282019%29.svg/200px-Fox_Sports_logo_%282019%29.svg.png' },
  { keywords: ['real madrid', 'rmtv'], logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/200px-Real_Madrid_CF.svg.png' },
  { keywords: ['willow'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Willow_TV.png/200px-Willow_TV.png' },
  { keywords: ['fancode'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/FanCode_logo.svg/200px-FanCode_logo.svg.png' },
  { keywords: ['zee bangla'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Zee_Bangla.svg/200px-Zee_Bangla.svg.png' },
  { keywords: ['star jalsha'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Star_Jalsha.svg/200px-Star_Jalsha.svg.png' },
  { keywords: ['colors bangla'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Colors_Bangla_logo.svg/200px-Colors_Bangla_logo.svg.png' },
  { keywords: ['btv'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/BTV_Logo.svg/200px-BTV_Logo.svg.png' },
  { keywords: ['goldmines'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Goldmines_Telefilms_logo.png/200px-Goldmines_Telefilms_logo.png' },
  { keywords: ['sony max'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Sony_MAX_logo.svg/200px-Sony_MAX_logo.svg.png' },
  { keywords: ['cartoon network'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/200px-Cartoon_Network_2010_logo.svg.png' },
  { keywords: ['quran'], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Saudi_Quran_Channel_logo.svg/200px-Saudi_Quran_Channel_logo.svg.png' }
];

export function getChannelLogo(name = '', m3uLogo = '') {
  // If we have a valid M3U logo URL, use it first
  if (m3uLogo && m3uLogo.trim().startsWith('http')) {
    return m3uLogo.trim();
  }

  // Normalize name for lookup (lowercase and strip multiple spaces)
  const cleanName = (name || '').toLowerCase().replace(/\s+/g, ' ').trim();

  // Try exact lookup first
  if (LOGO_DICTIONARY[cleanName]) {
    return LOGO_DICTIONARY[cleanName];
  }

  // Try matching against our keys (e.g. if name is "Somoy TV HD" and key is "somoy tv")
  for (const [key, value] of Object.entries(LOGO_DICTIONARY)) {
    if (cleanName.includes(key) || key.includes(cleanName)) {
      // Ensure it is a valid match, not a partial mismatch (e.g. 'caze' matching 'caze tv')
      if (Math.abs(key.length - cleanName.length) < 8) {
        return value;
      }
    }
  }

  // Try matching against our fallback keyword array
  const matched = FALLBACK_LOGO_MAP.find(item => 
    item.keywords.some(keyword => cleanName.includes(keyword))
  );

  if (matched) {
    return matched.logo;
  }

  // Default fallback to a high-quality general sports TV channel logo
  return 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/200px-2026_FIFA_World_Cup_emblem.svg.png';
}
